vaadin.launch-browser=true
spring.application.name=demo
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=APP_DEV;encrypt=false;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=Sa@2026Secure!
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# Gmail mail server
spring.mail.host=smtp.gmail.com
spring.mail.port=465


# Gmail authentication
spring.mail.properties.mail.smtp.auth=true

# TLS
#spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

logging.level.org.eclipse.angus.mail=DEBUG
logging.level.org.springframework.mail=DEBUG
logging.level.jakarta.mail=DEBUG

# Base URL of your app (change when deployed)
app.base-url=https://expense-tracker-1-fcfp.onrender.com

# Folder where images are stored
app.upload-dir=uploads

spring.mail.properties.mail.debug=true

