spring:   # Root namespace for Spring Boot configuration //Google Cloud Consol-->web site
  security:   # All security-related settings
    oauth2:   # Enable OAuth2 client support
      client:   # Define OAuth2 client registrations
        registration:   # Section for registering providers (Google, GitHub, etc.)
          google:   # Name of the provider → "google"
            client-id: 18863193940-lpl7l6kgn8ldtuk81p3500ahhldu2v04.apps.googleusercontent.com   # Your real Client ID   # Your Google OAuth2 Client ID (from Google Cloud Console)
            client-secret: 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   # Your Google OAuth2 Client Secret (keep safe!)
            scope: openid, profile, email   # What info you want from Google:
              # - openid → identity
              # - profile → basic user info (name, picture)
            # - email → user’s email address
            redirect-uri: "{baseUrl}/login/oauth2/code/google"   # Where Google sends user after login
              # {baseUrl} auto-replaced with your app URL
            # Must match redirect URI in Google Cloud Console
        provider:   # Section for provider-specific details
          google:   # Provider name → "google"
            issuer-uri: https://accounts.google.com   # Google’s OpenID Connect issuer URI
            # Used by Spring Security to fetch keys & validate tokens

  #logging:
    #level:
    # org.springframework.security: TRACE
    # org.springframework.web: DEBUG